### ISSUE TITLE
[play-hrpsysfile.l] neuro_vmになったことで *servo-state-msg* が作られない

### ISSUE THREAD

**Issue by ketaro-m** [kindsenior/control_tools#6]
サーボ系をneuro_vmに移行したことで`/shm_servo_state`がpublishされず，https://github.com/kindsenior/control_tools/blob/master/play-hrpsysfile.l#L666 でスタックします．また，`*servo-state-msg*`が作られないので，`save-shm-log`などが機能しません．

現在，JAXONで広く使われているhrpsysでは
https://gitlab.jsk.imi.i.u-tokyo.ac.jp/hiraoka/auto_stabilizer_config/-/blob/master/auto_stabilizer_config/launch/hrpsys.launch#L239 で trans_status_publisher.cpp を起動しているのですが，neuro_vmを起動した場合には [この分岐](https://github.com/jsk-ros-pkg/trans_system/blob/master/trans_ros_bridge/src/trans_status_publisher.cpp#L124) に入らないので，`/shm_servo_state`がpublishされません．

trans_vmでサーボshmを起動した場合は上記の分岐に入るので，`/shm_servo_state`がpublishされて `*servo-state-msg*`が作られます．

play-hrpsysfile.l を変更して別のトピックをsubscribeするようにすべきなのか，そもそもtrans_ros_bridgeが対応できていないという話なのか分かっていないのですが，ひとまずここに書かせていただきました．

**Comment by Naoki-Hiraoka** [comment]
https://gitlab.jsk.imi.i.u-tokyo.ac.jp/neuro_vm/neuro_vm/-/merge_requests/16 で直ります。

**Comment by ketaro-m** [comment]
ありがとうございます．

@kindsenior 
https://gitlab.jsk.imi.i.u-tokyo.ac.jp/neuro_vm/neuro_vm/-/merge_requests/16#note_3375

> ROSの世界ではcontrol_tools以外でservo_stateを使うとこるがない

が正しくて，control_tools だけ変更するのであったとしても

> サーボオン・オフを判定して実験中に異常にサーボオフしたら勝手にsave-logする

という機能は無効にするということになるのでしょうか．

**Comment by kindsenior** [comment]
>>サーボオン・オフを判定して実験中に異常にサーボオフしたら勝手にsave-logする

>という機能は無効にするということになるのでしょうか．

必須の機能というほどでもないので，それがいいかなと思う．

ただ，
> ROSの世界ではcontrol_tools以外でservo_stateを使うとこるがない

は，現状ないということであって，将来的になくて普通ということではない（できる限りROS側で管理するのがよい）ということかなとは思ってます．

まあとにかくcontrol_toolsを使う人がcontrol_toolsを修正して，neuro_vm側で対応する時ではない気がしてます．

**Comment by Naoki-Hiraoka** [comment]
servo_stateが出ないのは将来困りそうなので，
https://github.com/jsk-ros-pkg/trans_system/blob/ae959464b683bce5c66f4a1c88e04d7be18e7b41/trans_ros_bridge/src/trans_status_publisher.cpp#L124 のif文チェックを消しても良いかも知れないです．

**Comment by ketaro-m** [comment]
>> ROSの世界ではcontrol_tools以外でservo_stateを使うとこるがない

> は，現状ないということであって，将来的になくて普通ということではない（できる限りROS側で管理するのがよい）ということかなとは思ってます．

現状，control_toolsでしかこの問題は起きておらず，かつその問題も根幹的な問題ではない(save-log必須の機能ではない)ということなので，
この問題だけが起きているうちは，control_tools使う人が都度修正して，control_tools以外のROSの世界で同様の問題が生じた場合は，neuro_vmないしはtrans_ros_bridgeを修正するという方針で行こうと思います．
